### ISSUE TITLE
profile system

### ISSUE THREAD

**Issue by Sebiche09** [Insanytil/Dev-Web-2024#15]

**Comment by Sebiche09** [comment]
- i add on profile a possibility to see personal information directly with backend
- i add default image to profile (unknown profile) and i add a function to upload a image but the functionnality is not operational.
- i create a card with company
- on card company, we can for now create a new company by putting information on form
- company creation work ! and if company is create, you have now some information about your company

**Comment by Nini1551** [comment]
* I can see my personal information directly from backend
* I see a default profile picture but i can add an image (but the site propose me to do it)
* I see the company card
* I should not see the company card while i'm not a producer.
* While I am a producer, i can create a company.

# To Rework
* A non producer could not see the creation company card
